import type { Metadata } from "next";
import "./styles/globals.css";
import NavBar from "@PortfolioApp/Components/NavBar";
import Footer from "@PortfolioApp/Components/FooterComponent";
import Image from "next/image";
import bgImage from "../../public/portfolio-background.webp";

export const metadata: Metadata = {
    title: "Portfolio app",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Image
                    src={bgImage}
                    alt="bg image missing"
                    className="min-h-dvh h-[100%] fixed top-0 left-0 z-[0] w-full object-cover backdrop-blur-[5px] "
                />
                <NavBar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
