import PROFESSIONAL_GROWTH from './PROFESSIONAL_GROWTH.webp';
import CONTINUOUS_LEARNING from './CONTINUOUS_LEARNING.webp';
import CREATIVE_PROBLEM_SOLVING from './CREATIVE_PROBLEM_SOLVING.webp';
import FULL_STACK_DEVELOPMENT from './FULL_STACK_DEVELOPMENT.webp';
import COLLABORATION_TEAMWORK from './COLLABORATION_TEAMWORK.webp';
import USER_CENTERED_DESIGN from './USER_CENTERED_DESIGN.webp';
import { StaticImageData } from 'next/image';
export const cardImages: Record<string, StaticImageData> = {
	PROFESSIONAL_GROWTH: PROFESSIONAL_GROWTH,
	CONTINUOUS_LEARNING: CONTINUOUS_LEARNING,
	CREATIVE_PROBLEM_SOLVING: CREATIVE_PROBLEM_SOLVING,
	FULL_STACK_DEVELOPMENT: FULL_STACK_DEVELOPMENT,
	COLLABORATION_TEAMWORK: COLLABORATION_TEAMWORK,
	USER_CENTERED_DESIGN: USER_CENTERED_DESIGN,
};
